from importlib.metadata import PackageNotFoundError, version

from any_llm.any_llm import AnyLLM
from any_llm.api import (
    acancel_batch,
    acompletion,
    acreate_batch,
    aembedding,
    aimage_generation,
    alist_batches,
    alist_models,
    amessages,
    aresponses,
    aretrieve_batch,
    aretrieve_batch_results,
    aspeech,
    atranscription,
    cancel_batch,
    completion,
    create_batch,
    embedding,
    image_generation,
    list_batches,
    list_models,
    messages,
    responses,
    retrieve_batch,
    retrieve_batch_results,
    speech,
    transcription,
)
from any_llm.constants import LLMProvider
from any_llm.exceptions import (
    AnyLLMError,
    AuthenticationError,
    BatchNotCompleteError,
    ContentFilterError,
    ContentFilterFinishReasonError,
    ContextLengthExceededError,
    InvalidRequestError,
    LengthFinishReasonError,
    MissingApiKeyError,
    ModelNotFoundError,
    ProviderError,
    RateLimitError,
    UnsupportedParameterError,
    UnsupportedProviderError,
)
from any_llm.types.batch import Batch, BatchRequestCounts, BatchResult, BatchResultError, BatchResultItem
from any_llm.types.completion import ParsedChatCompletion, ParsedChatCompletionMessage, ParsedChoice

try:
    __version__ = version("any-llm-sdk")
except PackageNotFoundError:
    __version__ = "0.0.0-dev"


__all__ = [
    "AnyLLM",
    "AnyLLMError",
    "AuthenticationError",
    "Batch",
    "BatchNotCompleteError",
    "BatchRequestCounts",
    "BatchResult",
    "BatchResultError",
    "BatchResultItem",
    "ContentFilterError",
    "ContentFilterFinishReasonError",
    "ContextLengthExceededError",
    "InvalidRequestError",
    "LLMProvider",
    "LengthFinishReasonError",
    "MissingApiKeyError",
    "ModelNotFoundError",
    "ParsedChatCompletion",
    "ParsedChatCompletionMessage",
    "ParsedChoice",
    "ProviderError",
    "RateLimitError",
    "UnsupportedParameterError",
    "UnsupportedProviderError",
    "acancel_batch",
    "acompletion",
    "acreate_batch",
    "aembedding",
    "aimage_generation",
    "alist_batches",
    "alist_models",
    "amessages",
    "aresponses",
    "aretrieve_batch",
    "aretrieve_batch_results",
    "aspeech",
    "atranscription",
    "cancel_batch",
    "completion",
    "create_batch",
    "embedding",
    "image_generation",
    "list_batches",
    "list_models",
    "messages",
    "responses",
    "retrieve_batch",
    "retrieve_batch_results",
    "speech",
    "transcription",
]
