"""Initial migration with all models.

Revision ID: 28d153c22616
Revises:
Create Date: 2025-10-22 13:22:06.718969

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28d153c22616"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("budget_id", sa.String(), nullable=False),
        sa.Column("max_budget", sa.Float(), nullable=True),
        sa.Column("budget_duration", sa.String(), nullable=True),
        sa.Column("budget_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("budget_id"),
    )
    op.create_table(
        "model_pricing",
        sa.Column("model_key", sa.String(), nullable=False),
        sa.Column("input_price_per_million", sa.Float(), nullable=False),
        sa.Column("output_price_per_million", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("model_key"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("spend", sa.Float(), nullable=False),
        sa.Column("budget_id", sa.String(), nullable=True),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.budget_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.add_column("api_keys", sa.Column("user_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_foreign_key("fk_api_keys_user_id", "api_keys", "users", ["user_id"], ["user_id"])
    op.add_column("usage_logs", sa.Column("user_id", sa.String(), nullable=True))
    op.alter_column("usage_logs", "api_key_id", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_usage_logs_user_id"), "usage_logs", ["user_id"], unique=False)
    op.create_foreign_key("fk_usage_logs_user_id", "usage_logs", "users", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_usage_logs_user_id", "usage_logs", type_="foreignkey")
    op.drop_index(op.f("ix_usage_logs_user_id"), table_name="usage_logs")
    op.alter_column("usage_logs", "api_key_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("usage_logs", "user_id")
    op.drop_constraint("fk_api_keys_user_id", "api_keys", type_="foreignkey")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_column("api_keys", "user_id")
    op.drop_table("users")
    op.drop_table("model_pricing")
    op.drop_table("budgets")
    # ### end Alembic commands ###
