name: "Mark Stale Issues and PRs"

on:
  schedule:
    - cron: "0 0 * * *" # runs daily
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue has been marked stale due to 30 days of inactivity. It will be closed in 7 days if no further activity occurs."
          stale-pr-message: "This PR has been marked stale due to 30 days of inactivity. It will be closed in 7 days if no further activity occurs."
          exempt-issue-labels: "pinned,security"
          exempt-pr-labels: "work-in-progress"
